### ISSUE TITLE
Set Tea program options

### ISSUE THREAD

**Issue by testinfected** [charmbracelet/huh#101]
It would be nice to be able to set Tea program options. Currently we don't have to way to do that since programs are instantiated during `run()`.

One way would be to provide a `RunWith(*tea.Program)` method or something equivalent.

My use case is the following:
I'm using Huh for a CLI application and when running under CI I don't have access to a TTY. I'd like to be able to run my tests using the `WithInput` option to prevent the program from attempting to open a TTY.

Thanks

**Comment by testinfected** [comment]
Looking at the BubbleTea code, the above proposition would not work but having `RunWith(opts ...tea.ProgramOption) would

**Comment by caarlos0** [comment]
Maybe it's not needed: the form is a model, which you can then run as a regular bubbletea model, passing options as you need, e.g.: `tea.Run(form, options...)`

**Comment by testinfected** [comment]
Ah makes sense, will try that

Thanks @caarlos0

**Comment by testinfected** [comment]
I'm reopening since although I can workaround as @caarlos0 suggested, it forces to rewrite all the `Run` methods if I want to provide my our program with specific configuration options (e.g. without tty for CI runs).

**Comment by caarlos0** [comment]
hey @testinfected, sorry, what do you mean by "rewriting all the `Run` methods"? 

is your project OSS, or can you share an example of what you're doing?

**Comment by testinfected** [comment]
Unfortunately no the project is not open source, nevertheless I can share some details about what we're doing.

We have a CLI application for internal use. Some commands require interactions with the user (e.g. asking for confirmation, showing a spinner, showing interactive tables, and more).

We end-to-end test against the actual binary. In our CI those tests are run without a TTY and I want to setup the `tea.Program` with options `WithInput(nil)` and `WithoutRenderer()`.

We also want to be able (with a command line flag), to switch off ANSI sequences for capturing and processing of ouput (using `WithoutRenderer()`).

Currently the Run() commands create the program so I don't see a way of configuring the program with options except from rewriting the Run() commands, which in turn might require to fork and modify the source code.

If we add a e.g. `func (f *Form) RunWith/In(p *Program) error` that would solve my issue. Same for spinner.

Hope that helps understanding our issues. If you have any more questions I can provide additional details.

Thanks

**Comment by caarlos0** [comment]
see #109

**Comment by testinfected** [comment]
Great, many thanks

**Comment by testinfected** [comment]
Looks good to me
