### ISSUE TITLE
Tab Complete for Input Fields

### ISSUE THREAD

**Issue by ryan-timothy-albert** [charmbracelet/huh#105]
I'm wondering if it's possible to support tab completion for input fields. Ideally it would be possible to use tab completion when entering values like it is outside of the form.

It may already be possible to configure this and I am missing something.

Thanks in Advance!

**Comment by maaslalani** [comment]
Hi, this is already possible on the latest `huh@main`! Introduced in:
* #93 

We'll do a release soon which will make it available more widely but to try it out:

```
go get -u github.com/charmbracelet/huh@main
```

And then on your `Input` fields you can attach `Suggestions`:

```
huh.NewInput().Suggestions([]string{"foo", "bar", "baz"})
```

**Comment by ryan-timothy-albert** [comment]
Awesome I'll try that out thank you!

**Comment by ryan-timothy-albert** [comment]
Wondering if there is a general estimate on when that next release will be? Not urgent

**Comment by maaslalani** [comment]
Hey @ryan-timothy-albert! It should be next week!

**Comment by ryan-timothy-albert** [comment]
Hey @maaslalani 

Harcoded suggestions are working well. One follow up question we have that's come from our users is if there are plans to hook into more dynamic autocompletion. i.e. someone types `../`o we can suggest files in that directory that start with o.

**Comment by maaslalani** [comment]
Hey @ryan-timothy-albert, thanks for re-opening this issue. We want to create a system in huh that lets you re-evaluate any part of the form based on the user input as well.

This should encompass passing in new suggestions to `Suggestions`.

* #69

**Comment by ryan-timothy-albert** [comment]
Hi @maaslalani 

Thanks for the response. We do use the WithHideFunc internally. I'm totally following how this can help us populate suggestions based on live user input to a field though.

**Comment by ryan-timothy-albert** [comment]
Hey @maaslalani 

So currently we are supporting dynamic autocomplete with a fork like the following see [here](https://github.com/speakeasy-api/huh/commit/2d5885181c86d184e2f833be5a78a48f0b2050ad).

Here is the [callback function](https://github.com/speakeasy-api/speakeasy/blob/main/internal/charm/utils.go#L87) that we use.


I recognize there are some risks to exposing a callback like this from field_input especially if the user implements it incorrectly. I'm wondering if you'd be open to something like this in the main huh library, or perhaps a different approach to the problem.
