### ISSUE TITLE
Skippable notes

### ISSUE THREAD

**Issue by maaslalani** [charmbracelet/huh#107]
`Note` Fields should allow to automatically progress to the next field so that the user does not have to interactive with them.

This would be especially useful for using notes to separate fields in the same group.

**Comment by bzvestey** [comment]
Agreed, I would like to use notes to add more information in areas, and it would be nice to have them skipped when going through the form.

**Comment by maaslalani** [comment]
Solved by:

* https://github.com/charmbracelet/huh/pull/116
