### ISSUE TITLE
`Bug`: MultiSelect accessible mode allows selecting more options than the specified limit

### ISSUE THREAD

**Issue by anirudhaCodes** [charmbracelet/huh#114]
**Describe the bug**
In the `runAccessible` method of the MultiSelect field, there is a missing check for the limit when selecting options. This causes the accessible mode to allow selecting more options than the specified limit. This limit checkis handle in update method.

**To Reproduce**
1. Go to burger example of 'huh\examples\burger'
2. Run the form with `WithAccessible(true)`
3. Try to select more option than specified limit in multiselect field.
4. The accessible mode allows you to select more options than the specified limit.

**Expected behavior**
The accessible mode should enforce the specified limit on the number of options that can be selected, just like in the regular `Run` method (in update function).

**Screenshots**
In below image you can see that i can able to select more options than specified limit.
<img width="377" alt="image" src="https://github.com/charmbracelet/huh/assets/155895067/8bd035f0-6031-457a-aea6-56a0efa6cd8b">

Desktop :

Device : Laptop
OS : WIN 11
go Version : go 1.21.6 windows/amd64

**Proposed solution**

Option 1:

```diff
func (m *MultiSelect[T]) runAccessible() error {
	m.printOptions()

	var choice int
	for {
		fmt.Printf("Select up to %d options. 0 to continue.\n", m.limit)

		choice = accessibility.PromptInt("Select: ", 0, len(m.options))
		if choice == 0 {
			m.finalize()
			err := m.validate(*m.value)
			if err != nil {
				fmt.Println(err)
				continue
			}
			break
		}
+		if !m.options[choice-1].selected && m.limit > 0 && m.numSelected() >= m.limit {
+			fmt.Printf("You can't select above %d options. 0 to continue.\n", m.limit)
+			continue
+		}
		m.options[choice-1].selected = !m.options[choice-1].selected
		if m.options[choice-1].selected {
			fmt.Printf("Selected: %s\n\n", m.options[choice-1].Key)
		} else {
			fmt.Printf("Deselected: %s\n\n", m.options[choice-1].Key)
		}

		m.printOptions()
	}

	var values []string

	for _, option := range m.options {
		if option.selected {
			*m.value = append(*m.value, option.Value)
			values = append(values, option.Key)
		}
	}

	fmt.Println(m.theme.Focused.SelectedOption.Render("Selected:", strings.Join(values, ", ")+"\n"))
	return nil
}
```
Option 2:
Alternatively, a separate checker function can be introduced to handle the all the limit check. This function can be called before toggling the selected state of an option in the `runAccessible` method and in `Run` method (update function).

Assign this to me.

**Comment by anirudhaCodes** [comment]
Is it intended to disregard the `MultiSelect` limit in the accessible model?

**Comment by maaslalani** [comment]
> Is it intended to disregard the `MultiSelect` limit in the accessible model?

Hi! No this is not intended but rather a bug. Thank you for catching this!

**Comment by anirudhaCodes** [comment]
Should i work on proposed solution?

I found out that CharLimit in NewText is also being ignored by the accessible mode

**Comment by maaslalani** [comment]
We would happily accept a PR to fix this! Great catch on the CharLimit as well!

**Comment by maaslalani** [comment]
Thank you so much for the awesome contributions on accessible mode @anirudhaCodes.

I'm going to close this issue since it was solved by:

* #125 
* #126

If anything else pops up, feel free to re-open this issue or make a new one!

**Comment by anirudhaCodes** [comment]
I forgot to close this issue after my PR merge. 
Missed you @maaslalani for last 2 weeks.
