### ISSUE TITLE
Bug: If Skippable First field is in first group of form then it  is not getting Skipped on Toggling Back

### ISSUE THREAD

**Issue by anirudhaCodes** [charmbracelet/huh#120]
**Describe the bug**
When navigating through a form and currently in the first group, if the first field is skippable and the form starts with the second field due to the skipping of the first field , But toggling back does not correctly handle the skippable state of the first field .

**To Reproduce**
1. Go to create form where 1st field is skippable but 2nd field is not skippable.
2. The form will open with current field as 2nd field (expected behavior). 
3. Now toggle back (using shift + tab), you will see that the bottom helper command shows command for skippable field.

**Expected behavior**
Toggling back to the first field in the first group should correctly handle the skippable state. If the first field was initially skipped, it should still be skippable while toggling back.

**Screenshots**
intial state of form: (it starts with 2nd field because 1st field is skippable):
<img width="305" alt="image" src="https://github.com/charmbracelet/huh/assets/155895067/ac8a76ef-e704-48a7-b983-4002c979d633">
Toggle back state of form: (bottom command gets change to commands of the skippable component):
<img width="338" alt="image" src="https://github.com/charmbracelet/huh/assets/155895067/4e472938-4c44-4c5c-981c-f0176f76afea">

Desktop :

Device : Laptop
OS : WIN 11
go Version : go 1.21.6 windows/amd64

**Comment by maaslalani** [comment]
Thank you for the bug report @anirudhaCodes, we will fix!

**Comment by anirudhaCodes** [comment]
@maaslalani 
Solution works. 
But if a group has only one field which is skippable then it doesn't skip the group.
and  if a group has more than one field (All of them are skippable) then it skip the group.

If last group of the form contains all skippable fields then the form skips the first whole group
