### ISSUE TITLE
Add search for select

### ISSUE THREAD

**Issue by itaispiegel** [charmbracelet/huh#147]
I thought it would be a nice idea to add the ability to search items in a select field. When there are a lot of items in it, it could be too much effort to scroll all the items until I reach the item I want.
I thought it would be nice to be able to search the items in the list.

**Comment by maaslalani** [comment]
Hi! I believe what you're looking for is the filter option. On a select field if you press `/` it will let you search through the options.

<img width="737" alt="image" src="https://github.com/charmbracelet/huh/assets/42545625/35642185-b275-4d7c-bda3-c835bdc35522">
