### ISSUE TITLE
Request: Hidden text input

### ISSUE THREAD

**Issue by KyleTryon** [charmbracelet/huh#150]
**Is your feature request related to a problem? Please describe.**
I am attempting to allow users to input sensitive information, such as API keys, but currently, this displays the information on screen.

**Describe the solution you'd like**
Add either a `Hidden()` and/or `Mask()` method to the input filed.

**Hidden input:**
```go
huh.NewInput().
    Title("Enter your Credentials").
    Prompt("API Key:").
    Hidden().
    Value(&apiKey)
```

This would prevent the characters typed from appearing on the screen, similar to how entering your user passwd on linux would be.

**Masked Input:**
```go
huh.NewInput().
    Title("Enter your Credentials").
    Prompt("API Key:").
    Hidden().
    Value(&apiKey)
```

This would mask the input, similar to web forms, replacing `password` with `********`

**Describe alternatives you've considered**
I have not seen yet a standalone bubble tea component that could be easily integrated with huh.

**Additional context**
I am currently working on a project that needs this. I will be moving past it for now, but when I come back to it, if this is still needed, I may contribute the solution.

**Comment by jon4hz** [comment]
You can use:
```go
huh.NewInput().
    Title("Enter your Credentials").
    Prompt("API Key:").
    Password(true).
    Value(&apiKey)
```

**Comment by maaslalani** [comment]
Hey @KyleTryon, thanks for creating this issue! As @jon4hz, I think you're looking for the `Password` attribute. Let us know if this solves your problem!

**Comment by KyleTryon** [comment]
Yes thank you folks! Not sure how I missed that. Perfect. 🤘
