### ISSUE TITLE
b6644a1 breaks custom theming 

### ISSUE THREAD

**Issue by jon4hz** [charmbracelet/huh#155]
**Describe the bug**
The commit b6644a1fd11d5504c85b69b69034977f88a97a26 for some reason seems to break my custom theming.

I'm using the following code to create my theme based on the `huh.ThemeBase()`:

```go
package theme

import (
	_ "unsafe" // used for the hacky interalCopy linking.

	"github.com/charmbracelet/huh"
	"github.com/charmbracelet/lipgloss"
)

// maybe a bit hacky but the copy method isn't exported for some reason
//
//go:linkname internalCopy github.com/charmbracelet/huh.Theme.copy
func internalCopy(huh.Theme) huh.Theme

// MyCompany is a mycompany flavored huh theme.
func MyCompany() *huh.Theme {
	t := *huh.ThemeBase()
	t = internalCopy(t)

	var (
		normalFg = lipgloss.AdaptiveColor{Light: "235", Dark: "252"}
		blue     = lipgloss.AdaptiveColor{Light: "#7d86f7", Dark: "#7d86f7"}
		darkBlue = lipgloss.AdaptiveColor{Light: "#000b7b", Dark: "#000b7b"}
		green    = lipgloss.AdaptiveColor{Light: "#7afbc4", Dark: "#7afbc4"}
		red      = lipgloss.AdaptiveColor{Light: "#FF4672", Dark: "#ED567A"}
	)

	f := &t.Focused
	f.Base = f.Base.BorderForeground(lipgloss.Color("238"))
	f.Title.Foreground(blue).Bold(true)
	f.NoteTitle.Foreground(blue).Bold(true).MarginBottom(1)
	f.Description.Foreground(lipgloss.AdaptiveColor{Light: "", Dark: "243"})
	f.ErrorIndicator.Foreground(red)
	f.ErrorMessage.Foreground(red)
	f.SelectSelector.Foreground(green)
	f.Option.Foreground(normalFg)
	f.MultiSelectSelector.Foreground(green)
	f.SelectedOption.Foreground(green)
	f.SelectedPrefix = lipgloss.NewStyle().Foreground(lipgloss.AdaptiveColor{Light: "#02CF92", Dark: "#02A877"}).SetString("✓ ")
	f.UnselectedPrefix = lipgloss.NewStyle().Foreground(lipgloss.AdaptiveColor{Light: "", Dark: "243"}).SetString("• ")
	f.UnselectedOption.Foreground(normalFg)
	f.FocusedButton.Foreground(darkBlue).Background(green)
	f.Next = f.FocusedButton.Copy()
	f.BlurredButton.Foreground(normalFg).Background(lipgloss.AdaptiveColor{Light: "252", Dark: "237"})

	f.TextInput.Cursor.Foreground(green)
	f.TextInput.Placeholder.Foreground(blue)
	f.TextInput.Prompt.Foreground(green)
	f.TextInput.Text.Foreground(blue).Bold(true)

	t.Blurred.Base.BorderStyle(lipgloss.HiddenBorder())

	return &t
}
```

And this to create a custom form:
```go
func ConfirmForm(title, desc string, confirm *bool) *huh.Form {
	return huh.NewForm(
		huh.NewGroup(
			huh.NewConfirm().
				Title(title).
				Description(desc).
				Affirmative("Yes!").
				Negative("No.").
				Value(confirm),
		),
	).WithTheme(theme.MyCompany())
}
```

When I `go get` huh at commit 2d49f54ef7379ebb21cbbcd232957203160b7772 this approach works perfectly fine. However, when I checkout b6644a1fd11d5504c85b69b69034977f88a97a26 my custom theme breaks and the default huh theme is used.

**Expected behavior**
I expected huh to use my custom theme.

**Additional context**
I think this happens because the `huh.NewConfirm()` constructor sets the `huh.ThemeCharm()` by default. So `theme` is never actually nil.

**Comment by maaslalani** [comment]
> I think this happens because the huh.NewConfirm() constructor sets the huh.ThemeCharm() by default. So theme is never actually nil.

Ah nice, thanks for the detailed write up! We should likely remove the theme set in the constructor for Confirm.

**Comment by maaslalani** [comment]
@jon4hz Can you try on the latest commit of master again to see if theming applies? I removed the `ThemeCharm` from the `field_confirm`.

* https://github.com/charmbracelet/huh/commit/f5f5d1fd6e782921f96844b7edc947fb88e1cef9

**Comment by jon4hz** [comment]
> Ah nice, thanks for the detailed write up! We should likely remove the theme set in the constructor for Confirm.

Actually I think all constructors (input, select, etc) set the charm theme by default 😅.

And I just tested f5f5d1fd6e782921f96844b7edc947fb88e1cef9 and that seems to fix the issue but only if I set the theme on the confirm field directly. If I set my custom theme for the entire form, it's still ignored and the charm theme gets applied.

**Comment by maaslalani** [comment]
Thanks for the responses and help @jon4hz. I've reverted https://github.com/charmbracelet/huh/commit/51377e67546ce5fc4c2dc213250e53b6f45d1c88 for now and will come up with a better solution which solves all the edges cases and allows for individual theming of fields / groups, etc...

Going to close out this issue for now and open another one for theming.

**Comment by jon4hz** [comment]
Alright, thanks a lot for the quick response and fix!
