### ISSUE TITLE
Shift-Tab Not Working on Windows

### ISSUE THREAD

**Issue by lllama** [charmbracelet/huh#161]
It does now appear to be possible to go back in a form using `shift-tab` on Windows (using Windows Terminal).

**To Reproduce**
1. Run the BubbleTea example burger program.
2. Try to shift-tab back through the form.

**Expected behavior**
Moving back to the previous form input.

**Desktop:**
 - OS: Windows 11
 - Windows Terminal
 - Go 1.22

**Comment by meowgorithm** [comment]
Internal note that the fix here may simply be to use Bubble Tea on `master` as we merged https://github.com/charmbracelet/bubbletea/pull/878 recently, which overhauls input on Windows.

**Comment by lllama** [comment]
I shall have a look but I'm pretty sure I'm using `master` as I wanted window resizing support. I had a quick look at the code and I couldn't see the shift-tab key being handled anywhere. But that was only a quick look. I shall have a further dig and confirm that I'm on master.
