### ISSUE TITLE
Form Timeouts

### ISSUE THREAD

**Issue by korpa** [charmbracelet/huh#166]
**Is your feature request related to a problem? Please describe.**
I want a `Confirm` field automatically go on with the preselection after 5 seconds without user interaction. 

**Describe the solution you'd like**
Add a timeout config to the `Run` func

Some pseudo code:

```go
form := huh.NewForm(...)
form.Run(cfg{timeout: time.Duration})
```

```go
huh.NewInput().
...
Run(cfg{timeout: time.Duration})
```

If a timeout is set, a countdown starts when Run is called. When it finishes, `Run` does not block anymore and adds preselections to Values. 
As soon as a key is hit while countdown has not finished, count down stops and works as w/o timeout

**Describe alternatives you've considered**
--

**Additional context**
--

**Comment by maaslalani** [comment]
Hey! Thanks for creating this issue. We do actually need something like this as we recently removed timeout functionality for `gum` and would love to add it back due to the `huh?` transition.

**Comment by Delta456** [comment]
Hi, I am working on this and I would like a complete test case/example of this.

**Comment by maaslalani** [comment]
Hi @Delta456,

We would need to implement something like the following on the form, similar to the other options.

```go
func (f Form) WithTimeout(d time.Duration) Form
```

Then, when we `Run()` the form, we should pass a context to the `tea.Program` and cancel that context (use `context.WithTimeout`)

**Comment by Delta456** [comment]
This needs to be closed as it is implemented now.
