### ISSUE TITLE
Keep a form active after submitting.

### ISSUE THREAD

**Issue by dez11de** [charmbracelet/huh#167]
**Is your feature request related to a problem? Please describe.**
I would like to be able to stop the form from quitting after submitting. In my use case I want to use the form component to browse previously submitted forms as wel as create new responses.

**Describe the solution you'd like**
I'd like to be able to continue using the form after the user has submitted (or aborted it). This way I can use the form both as a way of getting the information and presenting the information.

**Additional context**
An small(ish) example of what I am trying to achieve can be found on [here](https://github.com/dez11de/huh_example.git)

**Comment by dez11de** [comment]
Fixed it by creating a new form and resetting the focus. 
Not sure why the reset of the focus is necessary but it seems to work.

Closing.

**Comment by Evidlo** [comment]
Just bumping this to see if the devs think of a cleaner way to handle this.
