### ISSUE TITLE
WithHidden and WithHiddenFunc for inputs

### ISSUE THREAD

**Issue by miniscruff** [charmbracelet/huh#169]
**Is your feature request related to a problem? Please describe.**
Conditional ~skip/~hiding of inputs within a group. I did see there is a WithHideFunc on the group level, and that there is a Skip() func on the Field interface. But in almost all cases its hard coded to false. ( The note type has some logic around it but select and inputs do not for example ). For my project I would just have a single form + group where depending on some options there may be some inputs that are skipped but its just one group. 

**Describe the solution you'd like**
~WithSkip and WithSkipFunc~ WithHidden and WithHiddenFunc options to configure fields lazily as the form+group progresses. ~I am a little confused on the difference between the "hide" value on groups and the "skip" value on fields and whether or not they are any different.~ Skip and hidden differences answered in the comments.

**Describe alternatives you've considered**
Use the group level hide option for every input option to take advantage of the hide func system. But output the results of the group after words or something so you know what you already input. You won't be able to go back or anything without closing the whole form and restarting, which I believe the form/group would provide.

**Additional context**
This is for my project changie if that helps at all, the idea is that based on some config + previous answers you may or may not have other options later on.

I can give a try at contributing as well, just prefer to make an issue first of course.

**Comment by maaslalani** [comment]
Hey @miniscruff to answer your question about `Hide` vs `Skip`.

* `Hide` does not display the group (field in the future)
* `Skip` displays the field but does not allow the user to interact with it. Currently this is only used for informational `Note` fields.

**Comment by miniscruff** [comment]
> Hey @miniscruff to answer your question about `Hide` vs `Skip`.
>     * `Hide` does not display the group (field in the future)
>     * `Skip` displays the field but does not allow the user to interact with it. Currently this is only used for informational `Note` fields.

OOOHHHH, ok cool, I half guessed something like that. My feature request would be more adding "Hide" to Fields then. Is that in the backlog already, I can't say I saw it.

**Comment by miniscruff** [comment]
Updated to be about hidden and not skip.

**Comment by miniscruff** [comment]
> Hey @miniscruff to answer your question about `Hide` vs `Skip`.
> 
> * `Hide` does not display the group (field in the future)
> * `Skip` displays the field but does not allow the user to interact with it. Currently this is only used for informational `Note` fields.

Do you think adding the hide option is valid? I can work on this if so.

**Comment by miniscruff** [comment]
Going to close as #69 replaces my need for this entirely, looking forward to it.
