### ISSUE TITLE
Duplicate form fields in Bubble Tea example

### ISSUE THREAD

**Issue by meowgorithm** [charmbracelet/huh#171]
The Bubble Tea example renders with duplicate form fields. This appears to be a regression: the behavior exists on `main` (71f31c155b088b017794ab6c42dfefe03e08215b) and on `v0.3.0` the form renders correctly.

<img width="608" alt="Screenshot 2024-03-19 at 11 15 15 AM" src="https://github.com/charmbracelet/huh/assets/25087/a1ac4ecf-0ed1-45ee-80f5-d3ba1357afc4">

**Comment by maaslalani** [comment]
This is now fixed https://github.com/charmbracelet/huh/commit/0d406ca61af164836b2c0744e8aec180d72085ac
