### ISSUE TITLE
Dynamically add fields to group

### ISSUE THREAD

**Issue by dez11de** [charmbracelet/huh#177]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to add (and remove) fields to a group depending on the value of a field in the (same) group. 

**Describe the solution you'd like**
I would like to be able to be able to call some function like f.form.SomeGroup.AddField(someField) where someField is of huh.Field type. Removing a field would be done with something like f.form.SomeGroup.RemoveField("some_field_key")
For my use case it would be OK if the new field was added at the end of the field array.

**Describe alternatives you've considered**
I don't see any alternative.

**Comment by maaslalani** [comment]
Hey @dez11de, thanks for creating this issue. We're planning on adding a Dynamic Form system to `huh` to solve all dynamic form problems and we'll keep track of the issue here: https://github.com/charmbracelet/huh/issues/69, feel free to follow this issue for updates!
