### ISSUE TITLE
Shift-tab functionality in general is impossible to use with dynamic forms

### ISSUE THREAD

**Issue by iloveicedgreentea** [charmbracelet/huh#191]
**Describe the bug**
Consider this code

```go
huh.NewGroup(
	huh.NewMultiSelect[string]().
		Key(keyAccountSelection).
		Options(huh.NewOptions(m.appState.AccountIds...)...).
		Title("Account Selection").
		Validate(validateMultiSelect). // TODO: this blocks shift tab
		Value(&m.appState.SelectedAccountIds),
).WithHideFunc(func() bool { return shouldHideAccountSelection(m) }),
```

if validateMultiSelect has a check to see if the input is blank, then shift-tab to go back will be blocked. Right now I have to forego input validation.

There are also various issues with shift-tab in general if I am remaking the form and then scrolling with NextGroup like keeping/restoring state. Most of these issues are caused by not being able to access the underlying state of the form, because none of the fields are exported.

**To Reproduce**
use the code above and make a function that returns an error if the input is blank. Then try to shift-tab

**Expected behavior**
Shift-tab would take precedence over input validation or there is a way to access some internal flag to set it to be skippable

**Comment by iloveicedgreentea** [comment]
I found a way around it for now by adding shift+tab in my Update() function and calling PrevGroup, but this may not be perfect because sometimes I will want to go to a field instead of a group

**Comment by jbcpollak** [comment]
I have a similar issue, possibly the same: the documentation for Group says:

```
// Group is a collection of fields that are displayed together with a page of
// the form. While a group is displayed the form completer can switch between
// fields in the group.
//
// If any of the fields in a group have errors, the form will not be able to
// progress to the next group.
```

to me this implies you should be able to move between fields within group even when you have validation errors, but the form should not be submitted (move to the next group) until the errors are resolved. But right now, if the validation for a field fails, you can't move off the field.

This runs counter to the way HTML forms work and is a pretty frustrating experience for users.

**Comment by caarlos0** [comment]
should have been fixed by https://github.com/charmbracelet/huh/pull/285
