### ISSUE TITLE
Add minimum selected option for multi-select

### ISSUE THREAD

**Issue by tetienne** [charmbracelet/huh#199]
**Is your feature request related to a problem? Please describe.**
Force user to select at least n options when using the multi-select.

**Describe the solution you'd like**
Same as limit, but opposite case.

**Describe alternatives you've considered**
Check afterwhile the number of selected options.

**Additional context**
n/a

**Comment by maaslalani** [comment]
Hey I think this makes sense and we should maybe add it but have you tried checking the len of the options in validate as an alternative? That way you can control the error message returned etc...

**Comment by tetienne** [comment]
Oh thank you, I didn’t think at all about this built-in function.

```golang
		form := huh.NewForm(
			huh.NewGroup(
				huh.NewMultiSelect[string]().Title("Select the environment").Options(huh.NewOptions(allowedEnvs...)...).Value(&env).
					Validate(func(v []string) error {
						if len(v) == 0 {
							return fmt.Errorf("at least one environment must be selected")
						}
						return nil
					}),
			).WithHide(len(env) > 0),
			huh.NewGroup(
				huh.NewSelect[string]().Title("Select the application").Options(huh.NewOptions(repos...)...).Value(&app),
			).WithHide(app != ""),
		)

```

did the trick

![image](https://github.com/charmbracelet/huh/assets/8216238/eb594ac0-7160-46b7-8ba2-fd9016c96c79)

I’m totally fine with this.

**Comment by maaslalani** [comment]
Awesome let's keep it this way for now then, I think having more custom error messages is better to explain why you need a minimum, and to keep the surface area of the API down.
