### ISSUE TITLE
NewInput does not support utf characters

### ISSUE THREAD

**Issue by buffos** [charmbracelet/huh#203]
**Describe the bug**
Create a simple NewInput. I used Greek letters.
The label supports them fine. When I switch the keyboard to Greek characters, everything I type is shown as garbage.

**Expected behavior**
I expected what I typed to be shown correctly.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows 11
 - Browser: chrome
 - Version : latest

Tried both in Command Prompt, GitBash and Pwsh

![image](https://github.com/charmbracelet/huh/assets/9776567/ed1c7067-952d-4a6a-ad24-9504131d4048)

**Comment by meowgorithm** [comment]
@buffos Does this happens with Bubble Tea on `master`? We merged some input improvements on Windows recently which may fix your issue.

```go
go get github.com/charmbracelet/bubbletea@master`
```

**Comment by buffos** [comment]
> @buffos Does this happens with Bubble Tea on `master`? We merged some input improvements on Windows recently which may fix your issue.
> 
> ```go
> go get github.com/charmbracelet/bubbletea@master
> ```

This fixes the issue !!!

**Comment by buffos** [comment]
@meowgorithm 

This fixes the issue!!!

Thank you

**Comment by meowgorithm** [comment]
Credit here goes the great work of @erikgeiser with [coninput](https://github.com/erikgeiser/coninput) and @aymanbagabas for the acute implementation in Bubble Tea ✌️
