### ISSUE TITLE
Empty string as negative confirm should show only one affirmative button

### ISSUE THREAD

**Issue by ragazenta** [charmbracelet/huh#205]
**Is your feature request related to a problem? Please describe.**

Previously we use `gum confirm` with empty string `--negative=""` . It showed only one button. But now `gum` use `huh` and this undo https://github.com/charmbracelet/gum/pull/175.

**Describe the solution you'd like**

Please redo https://github.com/charmbracelet/gum/pull/175 for `huh`.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by maaslalani** [comment]
Thanks so much for this issue! I'll make the appr

**Comment by maaslalani** [comment]
Hey @ragazenta this was added to `huh` by the way!

https://github.com/charmbracelet/huh/commit/1a310fe0c5604cb09e0d7f82b22f73c22971a56f

**Comment by ragazenta** [comment]
Great thanks. Looking forward for the next version of `gum` including this change.
