### ISSUE TITLE
Foreground color not working on new line

### ISSUE THREAD

**Issue by edumaxsantos** [charmbracelet/huh#221]
**Describe the bug**
When trying out the example, everything works fine until you get multiple toppings and they go to a new line. On the new line, the style is not being applied.

**To Reproduce**
Get the example code and apply multiple toppings.

**Expected behavior**
The text "Lettuce, Tomatoes, Jalapeños, and Cheese" should be pink, but the foreground style is applied only up to "Tomatoes,"

**Screenshots**
![image](https://github.com/charmbracelet/huh/assets/10568807/618fa4f6-6528-464e-b376-3114ba3d865d)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Terminal: Windows Terminal with Powershell

**Comment by maaslalani** [comment]
Hey thanks for this issue, this is a problem with lipgloss and wrapping styles around borders.

* https://github.com/charmbracelet/lipgloss/issues/85

**Comment by maaslalani** [comment]
Closing this as we need to solve it on the lipgloss side.
