### ISSUE TITLE
Theme not applied to input

### ISSUE THREAD

**Issue by rew1nter** [charmbracelet/huh#239]
**Describe the bug**
Isn't this code supposed to change the theme? I'm still seeing the default theme in terminal
```
	huh.NewInput().
		Title("The domain").
		Prompt("> ").
		Value(&domain).
		WithTheme(huh.ThemeBase16()).
		Run()
```

**Comment by maaslalani** [comment]
Hi @rew1nter, can you confirm this is fixed in the latest release of `huh?`. If not, please re-open this issue!
