### ISSUE TITLE
Empty confirmation considered invalid in accessible mode

### ISSUE THREAD

**Issue by testinfected** [charmbracelet/huh#264]
**Describe the bug**
When using the confirm field in accessible mode, user gets prompted to:

`Choose [y/N]:`

But when pressing enter, I was expecting the N choice to apply whereas I get:

```
Choose [y/N]:
invalid input. please try again
Choose [y/N]:
```

Looking at the code `parseBool` in `accessibility.go` expects exactly one of "y,", "yes","n" or "no". So the default value does not apply.

**Comment by testinfected** [comment]
WDYGT?

Thanks

**Comment by jaredallard** [comment]
Also running into this 😢
