### ISSUE TITLE
bug: note.render should escape everything in code block

### ISSUE THREAD

**Issue by c4po** [charmbracelet/huh#288]
**Describe the bug**

I need to render a text containing code in the note description. However, the characters `_` and `*` are still being treated as control signals instead of as part of the code text.

**To Reproduce**

```
huh.NewGroup(
huh.NewNote().
Title("Please verify the code here").
Description("code start here:"+
"`error_message: something with *`")
)
```

**Expected behavior**

it should have 
```
code start here:
error_message: something with *
```

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version 0.4.2

**Comment by maaslalani** [comment]
This is now fixed in https://github.com/charmbracelet/huh/commit/c97dfadca72f8831bc7ebea1cb91070e3ec117e4

**Comment by c4po** [comment]
I guess the fix introduce a new bug.
```
huh.NewGroup(
huh.NewNote().
Title("Please verify the code here").
Description("code start here:"+
"`error_message: something with *`")
)
```
will render the last back quotes instead treat it as end of code block.
```
code start here:
error_message: something with *`
```
