### ISSUE TITLE
Dynamic fields don't update when form is active

### ISSUE THREAD

**Issue by chase-crumbaugh** [charmbracelet/huh#314]
**Describe the bug**
When using, for example, `DescriptionFunc`, the active form field never gets its value updated. This is particularly noticeable when using `*Func` on the first field in a group, in which case the function is _never_ evaluated and the value is left blank (in this example, the description never populates).

**To Reproduce**
```go
count := 0
go func() {
	for {
		count++
		time.Sleep(1 * time.Second)
	}
}()

descriptionFunc := func() string {
	return fmt.Sprintf("The count is: %d", count)
}

err := huh.NewForm(huh.NewGroup(
	huh.NewInput().
		Title("Fill in the input").
		DescriptionFunc(descriptionFunc, &count),
	huh.NewInput().
		Title("Fill in the input").
		DescriptionFunc(descriptionFunc, &count),
)).Run()
```

**Expected behavior**
Both descriptions should update.

**Screenshots**

![CleanShot 2024-07-16 at 16 04 51@2x](https://github.com/user-attachments/assets/642a4214-53dd-43aa-ab3c-62d7b05b6e15)

**Comment by meowgorithm** [comment]
Very interesting. I can reproduce this.

**Comment by maaslalani** [comment]
This is now fixed in https://github.com/charmbracelet/huh/commit/8470c3c3d2d0458e3627ae901cc1df39318b2bfd
