### ISSUE TITLE
Dynamic options in Select do not display when not bound to another field

### ISSUE THREAD

**Issue by ktzanev** [charmbracelet/huh#316]
### Issue Description

The following code produces an empty select (expected "mango", "papaya", "durian"):

```go
// Example of using huh with dynamic options
package main

import (
	"fmt"

	"github.com/charmbracelet/huh"
)

func main() {
	var exotic bool = true
	var fruit string
	huh.NewForm(
		huh.NewGroup(
			// Uncommenting the line below makes the select work as expected
			// huh.NewConfirm().Title("Do you like exotic fruits?").Value(&exotic),
			huh.NewSelect[string]().
				Title("Select a fruit").
				OptionsFunc(func() []huh.Option[string] {
					if exotic {
						return huh.NewOptions("mango", "papaya", "durian")
					}
					return huh.NewOptions("apple", "cherry", "apricot")
				}, &exotic).
				Value(&fruit),
		),
	).Run()
	fmt.Println("Selected fruit:", fruit)
}
```

The same code, when the confirm line is uncommented, works as expected. It looks like if the binding (here `exotic`) is not the attached value of another field, it does not work. 

#### Steps to Reproduce
1. Run the provided code snippet.
2. Observe that the select field is empty.
3. Uncomment the confirm line.
4. Run the code again.
5. Observe that the select field now works as expected.

#### Expected Behavior
The select field should display "mango", "papaya", and "durian" when `exotic` is true, regardless of whether `exotic` is bound to another field. We should be able to bind variables that are not directly modified by huh, possibly by using something like `huh.Update(&variable)` after we change `variable`.

#### Actual Behavior
The select field is empty when `exotic` is not bound to another field.

#### Environment
- OS: Windows 10
- Go version: go1.22.5 windows/amd64
- huh version: 0.5.0

**Comment by maaslalani** [comment]
This is now fixed in https://github.com/charmbracelet/huh/commit/8470c3c3d2d0458e3627ae901cc1df39318b2bfd

**Comment by ktzanev** [comment]
@maaslalani I adapted [dynamic-increment](examples/dynamic/dynamic-increment/main.go) example to my MWE. 

```go
package main

import (
	"fmt"
	"time"

	"github.com/charmbracelet/huh"
)

func main() {
	var exotic bool = true
	go func() {
		for {
			time.Sleep(1 * time.Second)
			exotic = !exotic
		}
	}()
	var fruit string
	huh.NewForm(
		huh.NewGroup(
			huh.NewSelect[string]().
				TitleFunc(func() string {
					if exotic {
						return "Select an exotic fruit"
					}
					return "Select a fruit"
				}, &exotic).
				Height(7).
				OptionsFunc(func() []huh.Option[string] {
					if exotic {
						return huh.NewOptions("mango", "papaya", "durian")
					}
					return huh.NewOptions("apple", "cherry", "apricot")
				}, &exotic).
				Value(&fruit),
		),
	).Run()
	fmt.Println("Selected fruit:", fruit)
}
```

In a strange way, the changes are reflected only when I change my selection (<kbd>arrow down</kbd> or <kbd>arrow up</kbd>) not every seconds, as opposed to the Input field case in the original `dynamic-increment` example.
