### ISSUE TITLE
Confirm box default to Yes

### ISSUE THREAD

**Issue by Eduard-Voiculescu** [charmbracelet/huh#364]
Hi, would it be possible to implement the an option on the `huh.NewConfirm(...)` to default the value to the affirmative action instead of the Negative?

**Comment by Emyrk** [comment]
You can assign the `value` to `true` and it will default to the affirmative.

```golang
c := true
err := huh.NewConfirm().
	Title("Ready to continue?").
	Value(&c).
	Run()
```

**Comment by Eduard-Voiculescu** [comment]
Ok that makes sense, thank you
