### ISSUE TITLE
v0.5.0 broke withHide function

### ISSUE THREAD

**Issue by tetienne** [charmbracelet/huh#384]
**Describe the bug**
After upgrade to v0.5.0 `withHide` does not work as expected. Rollbacking to v0.4.2 solved my issue.

**To Reproduce**
```golang
form := huh.NewForm(
			huh.NewGroup(
				huh.NewSelect[string]().Title("Select the environment").Options(huh.NewOptions(allowedEnvs...)...).Value(&env),
			).WithHide(env != ""),
		)
```

**Expected behavior**
When `env` is empty, the select prompt must be displayed.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser N/A
 - Version N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by caarlos0** [comment]
just tried this on main, seems to be working as expected.

**Comment by tetienne** [comment]
Indeed, myself I’m not able to reproduce. Thx you anyway to have checked.

**Comment by tetienne** [comment]
@caarlos0 I was able to reproduce again.

And to "fix" this behavior, I have to use an intermediate variable:

```golang
hide := env != ""
form := huh.NewForm(
			huh.NewGroup(
				huh.NewSelect[string]().Title("Select the environment").Options(huh.NewOptions(allowedEnvs...)...).Value(&env),
			).WithHide(hide),
		)
```

And now it works as expected. I have also tried with `WithHideFunc` without success.
