### ISSUE TITLE
Shift+Tab doesn't go to previous field if Select OptionsFunc returns no options

### ISSUE THREAD

**Issue by Hector-Work** [charmbracelet/huh#422]
**Describe the bug**
If you are focused on a Select field where the OptionsFunc has not returned any options, Shift+Tab doesn't return focus to the previous field.

**To Reproduce**
Steps to reproduce the behaviour:
```go
search := ""

form := huh.NewForm(
  huh.NewGroup(
    huh.NewInput().
      Key("search").
      Value(&search).
      Title("Search"),
    huh.NewSelect[string]().
      OptionsFunc(func() []huh.Option[string] {
        return []huh.Option[string]{}
      }, &search).
      Title("Select"),
  ),
)

return form
```

**Expected behaviour**
The focus should return to the previous field.

Thank you :)

**Comment by caarlos0** [comment]
this seems to be fixed on main.

**Comment by semihbkgr** [comment]
@caarlos0 I don't think this issue is fixed on the main branch. The code sample provided in the description still seems buggy, at least based on my testing.
Could you @Hector-Work try running this example again on the main branch?
