### ISSUE TITLE
[Question] About text input validate

### ISSUE THREAD

**Issue by Darvyn** [charmbracelet/huh#45]
Hi Charm Team, 

it seems that the text validate() did not work as expected, is this correctly used ?

Thanks in advance:)

![image](https://github.com/charmbracelet/huh/assets/26133254/97289cff-df24-437c-b849-412a3ee396f1)

**Comment by maaslalani** [comment]
Hey @Darvyn, thanks so much for catching this! This is now fixed. Please let me know if it works for you know on the latest `main` (we will do a patch release soon). And, let me know if you run into any other bugs.

**Comment by Darvyn** [comment]
Thanks @maaslalani, it works perfectly now !

**Comment by Darvyn** [comment]
Hi @maaslalani, just found another bug related with the huh.NewText(), if we got a error from validation, then the cursor will still jump to the next field, and cannot shift+tab to back, I'm using the version 0.2.1

![image](https://github.com/charmbracelet/huh/assets/26133254/b065251b-32ce-4e61-a274-ff171109fad2)

**Comment by maaslalani** [comment]
@Darvyn Should be fixed now, it shouldn't let you go to the next field until the input is valid.

**Comment by Darvyn** [comment]
> @Darvyn Should be fixed now, it shouldn't let you go to the next field until the input is valid.

Great, thanks! @maaslalani
