### ISSUE TITLE
Style dont display correctly in Window Server 16

### ISSUE THREAD

**Issue by Orlandoiii** [charmbracelet/huh#457]
First of all, thank you so much for these amazing libraries! I started using them recently and immediately fell in love. The problem I'm facing is that the CLI looks perfect on my Windows 10 PC, but when I run it on the Windows server where it will be used, the colors and font look bad.  Is there something I need to configure at the Windows Server level?

**Comment by caarlos0** [comment]
This looks like a problem in the terminal emulator you're using on windows server.
Have you tried different ones?

In any case, without more context, not much we can do here... would need details, screenshots, etc.

Closing for now.
