### ISSUE TITLE
Input fields are not validating on Blur()

### ISSUE THREAD

**Issue by tlder** [charmbracelet/huh#47]
**Describe the bug**
When leaving an input field that has been created with a validation function, that validation function is not called.

**To Reproduce**
1. Create a form with an input field and validation function
2. Run the form
3. Enter invalid data into the input field
4. Leave the input field

**Expected behavior**
Expect to see the validation message displayed.

**Additional context**

See `field_input.go`:
```go
// Blur blurs the input field.
func (i *Input) Blur() tea.Cmd {
	i.focused = false
	i.textinput.Blur()
	return nil
}
```

**Comment by maaslalani** [comment]
Hey @tlder, what version of huh? are you using, this was recently fixed!

**Comment by tlder** [comment]
I was using an older version and it's working fine with the latest version. Apologies.

**Comment by maaslalani** [comment]
Thanks so much for confirming! And thanks for using huh!
