### ISSUE TITLE
Multi-select filtering

### ISSUE THREAD

**Issue by bryant-rh** [charmbracelet/huh#53]
[Question] How to implement multi-select filter

The test found that select filter is supported, but multi-select filter is not supported

**Comment by meowgorithm** [comment]
Hi! Yep, it looks the API has support for filtering however it still needs to be implemented. Good catch.

Note for implementors: this will also require some adjustments to the scrollable functionality that will be introduced in #75.

**Comment by maaslalani** [comment]
This is fixed by: https://github.com/charmbracelet/huh/pull/81
