### ISSUE TITLE
No wrapping on answer exceeding the terminal length

### ISSUE THREAD

**Issue by Iilun** [charmbracelet/huh#54]
**Describe the bug**
When using a single line input, if the answer length exceeds the terminal length, the cursor and the rest of the answer disappear.

**To Reproduce**
. Create an input 
. Input a very long answer 

**Expected behavior**
The exceeding characters are wrapped back to the next line.

**Screenshots**

https://github.com/charmbracelet/huh/assets/63926901/63b22dc0-77c0-438c-9bc1-cc6164ce4629

In this example the terminal stops at the right of the recording. I input only a's then delete some to come back in the frame.

**Desktop (please complete the following information):**
 - OS: macOS iTerm2 and Windows Powershell

**Additional context**
This may be an intended behavior but it seems not really user friendly

**Comment by meowgorithm** [comment]
Hi again. Just a note that this was fixed in #60 and is now available in v0.2.2.

**Comment by Iilun** [comment]
I tested it, its perfect, thanks !
