### ISSUE TITLE
Add the possibility to prefill the answer

### ISSUE THREAD

**Issue by Iilun** [charmbracelet/huh#55]
**Is your feature request related to a problem? Please describe.**
When creating prompts for editing a file for example, some values may already have been filled previously. Instead of only showing it as placeholder and needing the user to retype it, it would be great if it was there and editable.

**Describe the solution you'd like**
An option on input to add a string as a default value that will be prefilled in the input

**Comment by maaslalani** [comment]
Hey @Iilun, this is possible if you set the variable to the default value you want:

```go
value := "default value"

huh.NewInput().Value(&value).Run()
```

The field will be pre-filled with the value ("default value")

**Comment by vitor-mariano** [comment]
@maaslalani All the fields can be prefilled with `Value(&value)`, except `Select` and `MultiSelect`. I know I can achieve the same behavior with `huh.NewOption(...).Selected(true)`, but not with `huh.NewOptions`. Is this on purpose? Using `Value(&value)` would be interesting in scenarios when editing existing data and keeping consistency with other field types.

If this behavior is not intended, I'd love to open a PR fixing it!

**Comment by vitor-mariano** [comment]
@maaslalani before moving forward with the fix, what should happen if I have both value and `Selected(true)`? Eg

``` go
huh.NewMultiSelect().
    Options(
        huh.NewOption("lettuce", "lettuce"),
        huh.NewOption("tomatoes", "tomatoes").Selected(true),
        huh.NewOption("cheese", "cheese").Selected(true),
    ).
    Value(&toppings).
    Run()
```

**Comment by maaslalani** [comment]
I think the correct solution here would be to take the union of the two defaults. In this case all three would be selected as lettuce is in the toppings and the other two are selected.
