### ISSUE TITLE
Spinner gif in the readme doesn't loop

### ISSUE THREAD

**Issue by rahji** [charmbracelet/huh#65]
Hi, the spinner gif in the readme doesn't loop. So by the time you get to the section of the doc that has the gif, it's stuck at the last frame. The other gifs loop. I suppose this is more of a VHS question... I thought gifs recorded with VHS looped by default? In fact, I only see an option for the loop offset - nothing to disable looping. The demo.tape file that creates the spinner.gif doesn't mention looping at all. So why does the gif not loop? (Part VHS question, part bug report for the huh readme) :)

**Comment by vitor-mariano** [comment]
As far as I know, VHS loops by default. I guess the GIF in Readme is an old version. I just regenerated and it's now looping.
