### ISSUE TITLE
Long multi-select cuts off items

### ISSUE THREAD

**Issue by chilicat** [charmbracelet/huh#67]
**Describe the bug**
If you create e.g. a NewMultiSelect with a lot of items than it happens that some items are not visible (depending on the terminal hright

**To Reproduce**

```
package main

import (
	"strconv"

	"github.com/charmbracelet/huh"
)

func main() {
	result := []string{}
	list := []huh.Option[string]{}
	for i := 0; i < 30; i++ {
		item := "item-" + strconv.Itoa(i)
		list = append(list, huh.NewOption(item, item))
	}
	sel := huh.NewMultiSelect[string]().Options(list...).Value(&result)
	form := huh.NewForm(
		huh.NewGroup(sel).Description("Long List"),
	)
	err := form.Run()
	if err != nil {
		panic(err)
	}
}
```

Run in a terminal which can show less then 30 lines.

**Expected behavior**
List should be scrollable 

**Screenshots**

<img width="516" alt="Screenshot 2023-12-18 at 09 41 59" src="https://github.com/charmbracelet/huh/assets/476789/3cfe05de-4b65-4ae5-999e-ef475b1d0ac8">

**Desktop (please complete the following information):**
 - OSX, verson: v0.2.1

**Comment by kdssoftware** [comment]
I'm also having the same problem.
Maybe there is a workaround to this, if we can paginate using bubbletea?

**Comment by chilicat** [comment]
I was thinking of the viewport:
- https://github.com/charmbracelet/bubbles?tab=readme-ov-file#viewport
- https://github.com/charmbracelet/bubbles/tree/master/viewport

Maybe it would be possible to implement `SetMaxHeight` method to limit the visible list space:
```
huh.NewMultiSelect[string]().SetMaxHeight(10)
```

**Comment by meowgorithm** [comment]
Hi everyone. We have a candidate in #71 which should solve for this. Feel free to give it a look.
