### ISSUE TITLE
Don’t clear the prompt once confirmed

### ISSUE THREAD

**Issue by tetienne** [charmbracelet/huh#68]
**Is your feature request related to a problem? Please describe.**
Currently, when a  user confirms a prompt such as an input, or a select for instance, and confirm it, his choice is clear from the terminal. It’s kind of frustracting when you came back few times later and what to check what you did. 

**Describe the solution you'd like**
Add a parameter to each field, named for instance `Persist`, that will trigger this behavior.

**Describe alternatives you've considered**
N/A

**Additional context**
It was the default behavior of [survey](https://github.com/AlecAivazis/survey).

**Comment by vitor-mariano** [comment]
I think the problem with persisting the answers is that the user can move back and forth in groups. When this is not the case, you can easily achieve the same behavior by printing the group view as in the example below.

``` go
orderGroup := huh.NewGroup(
	huh.NewMultiSelect[string]().
		Title("Toppings").
		Options(
			huh.NewOptions("Letuce", "Tomatoes", "Jalapeños", "Cheese", "Vegan Cheese", "Nutella")...,
		).
		Value(&a.Toppings),

	huh.NewConfirm().Title("Extra sauce?").Value(&a.ExtraSauce),
)

form := huh.NewForm(orderGroup)

err := form.Run()
if err != nil {
	panic(err)
}

fmt.Println(orderGroup.WithShowHelp(false).View())
fmt.Println("Thank you for your order!")
```

![demo](https://github.com/charmbracelet/huh/assets/2306588/4aeb6c46-3504-4bda-989f-f1349fb19dbe)

**Comment by maaslalani** [comment]
@tetienne @tetienne-zenchef Is this issue still required or is the workaround sufficient?

**Comment by maaslalani** [comment]
Awesome @tetienne-zenchef! I'm going to close this issue for now, but please feel free to re-open or create a new issue if anything comes up!
