### ISSUE TITLE
Add a default selection to `Select`

### ISSUE THREAD

**Issue by guigui64** [charmbracelet/huh#70]
**Describe the bug**
I imagined `Value` could be used to set the default selection for a `Select` that way:

```go
foo := "two"
form := huh.NewForm(
	huh.NewGroup(
		huh.NewSelect[string]().Title("foo").Options(huh.NewOptions("one", "two", "three")...).Value(&foo),
	),
)
```

However, the form still selects `one` by default.

**To Reproduce**
See code snippet above.

**Expected behavior**
`two` selected by default.

**Comment by vitor-mariano** [comment]
This bug was reported [here](https://github.com/charmbracelet/huh/issues/55) and the [fix](https://github.com/charmbracelet/huh/pull/62) was merged yesterday. A new version should be released soon.

**Comment by maaslalani** [comment]
Hey @guigui64, thanks for reporting. Cutting a new release right now!

**Comment by maaslalani** [comment]
Released! https://github.com/charmbracelet/huh/releases/tag/v0.2.3
