### ISSUE TITLE
Serve Form

### ISSUE THREAD

**Issue by dezren39** [charmbracelet/huh#74]
It would be really cool if this tied into an Ssh or Wish instance so i could run 'huh serve' and then provide the ip address and anyone can go fill out the survey

**Comment by maaslalani** [comment]
Hey! This is definitely on our TODO list. Thanks so much for creating this issue!

**Comment by maaslalani** [comment]
One thing that we'll need to think about is how to collect the results.

**Comment by maaslalani** [comment]
Related issue: https://github.com/charmbracelet/wish/issues/236

**Comment by maaslalani** [comment]
Hey! Going to close this issue for now, we've added an example of how to run a form over SSH:

* https://github.com/charmbracelet/huh/blob/main/examples/ssh-form/main.go

In the future, we'll also make it much easier to do this sort of thing with `YAML` / `JSON` as well.
