### ISSUE TITLE
Reduce binary size

### ISSUE THREAD

**Issue by tetienne** [charmbracelet/huh#78]
**Is your feature request related to a problem? Please describe.**
While moving from survey to huh, I noticed a significant increase of my binary. 

* Before: 6.72 MB
* After. 9.08 MB

So an increase around 35%.

**Describe the solution you'd like**
Reduce the lib footprint.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by maaslalani** [comment]
Fixed by: https://github.com/charmbracelet/huh/pull/94
