### ISSUE TITLE
Conditional Prompt based on answers to the previous questions

### ISSUE THREAD

**Issue by sivaprasadreddy** [charmbracelet/huh#86]
A common scenario while building CLI tools is asking more/less questions based on the answer to a previous question.

For example: While generating an application, I would ask do they want to use SQL database. If they answer yes then only I would ask more questions such as which type of database, etc.

This is similar to Inquirer.js `when` feature https://github.com/SBoudrias/Inquirer.js/tree/master/packages/inquirer.

It would be a nice feature to implement a similar feature in huh.

**Comment by caarlos0** [comment]
I believe `WithHideFunc` does what you need:

- https://pkg.go.dev/github.com/charmbracelet/huh#Group.WithHideFunc
- https://github.com/charmbracelet/huh/blob/main/examples/hide/main.go

**Comment by sivaprasadreddy** [comment]
Yes, the `WithHideFunc` does what I need.

Example:

```
package main

import (
	"fmt"
	"github.com/charmbracelet/huh"
)

func main() {
	var useSqlDb bool
	var dbType string

	huh.NewForm(
		huh.NewGroup(huh.NewConfirm().Title("Do you want to use SQL database?").Value(&useSqlDb)),
		huh.NewGroup(
			huh.NewSelect[string]().
				Title("Choose your db type").
				Options(
					huh.NewOption("PostgreSQL", "postgresql"),
					huh.NewOption("MySQL", "mysql"),
					huh.NewOption("Oracle", "oracle"),
				).
				Value(&dbType),
		).WithHideFunc(func() bool {
			return !useSqlDb
		}),
	).Run()

	if useSqlDb {
		fmt.Println("Using SQL database of type " + dbType)
	} else {
		fmt.Println("Not using sql database")
	}
}
```
