### ISSUE TITLE
Input Suggestions

### ISSUE THREAD

**Issue by rusq** [charmbracelet/huh#89]
Hi team, it's me again! I promise I will stop creating these after I finish the migration from Survey.

**Is your feature request related to a problem? Please describe.**
Survey inputs had an option to add an input "suggestion", user could press the [Tab] key and they would get the list of suggestions.  This could be useful, if programme asks the user to input the existing filename (at least this is my use case).

I know that you already know what I'm writing about, but for completeness, here's the [link][1].

**Describe the solution you'd like**
I would like to be able to specify the function that would make an input suggestion to the user.

When there's one and only one suggestion, the tab should complete the input to the suggested value.
When there's more than one suggestion there are two possible options: first one is to show the list of all, or "top N" items that match the prefix entered, or, cycle through suggestions on each press of the [Tab] key, just like `cmd.exe` prompt does in Windows.

Please keep in mind that I just started using Huh, so maybe there's some bubble-magic that I'm unaware of that allows to implement this easily?

**Describe alternatives you've considered**
The alternative that I have considered is not using the suggestions, or implement it myself, which I haven't gotten around to, as I'm quite new to the whole charm.sh framework.

**Additional context**
Here's how it's implemented in [Survey][1] (copy/pasting here for convenience):
```go
file := ""
prompt := &survey.Input{
    Message: "inform a file to save:",
    Suggest: func (toComplete string) []string {
        files, _ := filepath.Glob(toComplete + "*")
        return files
    },
}
}
survey.AskOne(prompt, &file)
```
![demo](https://camo.githubusercontent.com/d42cedf79c61b9915f2e94dd6347a63ad461f2033833e950f1cbcef9a0fd240d/68747470733a2f2f692e696d6775722e636f6d2f5137504f7041312e676966)

Thank you for consideration.

[1]: https://github.com/AlecAivazis/survey#suggestion-options

**Comment by maaslalani** [comment]
Hey @rusq, we have the concept of `Suggestions` within the `textinput` bubble and can definitely expose this functionality to `huh`. Great call!

https://github.com/charmbracelet/bubbles/blob/master/textinput/textinput.go#L260-L269

**Comment by maaslalani** [comment]
Feature added in https://github.com/charmbracelet/huh/pull/93

**Comment by rusq** [comment]
Thank you!
